next:
    - follow: init
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["next", "-j$1"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

next-custom:
    - follow: init
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["npm", "-j$1"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

init:
    - name: nextjsspa
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["npm", "install"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`