next:
    - follow: init
      image: node:10
      commands:
      - ["next", "-j$1"]

next-custom:
    - follow: init
      image: node:10
      commands:
      - ["npm run", "-j$1"]

init:
    - name: nextjsspa
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["cd", "src"]
      - ["npm", "install"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`