# For more on configuration options, check http://goreleaser.com
project_name: <your_project_name>

builds:
- goos:
    - linux
  goarch:
    - 386
    - amd64

nfpms:
-
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  homepage:  <homepage>
  description: <short_description>
  maintainer: <maintainer>
  license: <license>
  formats:
  - rpm